function Resumo = gerar_tabela_resultados(res, ind, sinais, nome_alg, cenario_tag)
%GERAR_TABELA_RESULTADOS Monta a tabela-resumo para export em CSV
    t_sim = res.t_sim;
    n = numel(t_sim);
    t_min_col = sinais.t_min(t_sim(:));

    Resumo = table( ...
        repmat(string(nome_alg), n, 1), ...
        repmat(string(cenario_tag), n, 1), ...
        repmat(res.tempo_total, n, 1), ...
        repmat(ind.H2_total, n, 1), ...
        repmat(ind.Dbat_tot, n, 1), ...
        repmat(res.SOC_final*100, n, 1), ...
        repmat(ind.diff_media, n, 1), ...
        repmat(ind.diff_maxima, n, 1), ...
        repmat(ind.E_fc, n, 1), ...
        repmat(ind.E_pv, n, 1), ...
        repmat(ind.E_bat_d, n, 1), ...
        repmat(ind.E_bat_c, n, 1), ...
        repmat(ind.E_load, n, 1), ...
        repmat(ind.deficit_total_kWh, n, 1), ...
        repmat(ind.deficit_max_kW, n, 1), ...
        repmat(ind.deficit_n_passos, n, 1), ...
        t_min_col, ...
        res.Pfc_meta_hist(t_sim(:)), ...
        res.Pfc_refino_hist(t_sim(:)), ...
        ind.deficit_kW(:), ...
        'VariableNames', {'Algoritmo','Cenario','Tempo_s','H2_kg','Degradacao', ...
        'SOC_final_pct','Diff_meta_refino_media_kW','Diff_meta_refino_maxima_kW', ...
        'E_FC_kWh','E_PV_kWh','E_Bat_desc_kWh','E_Bat_carga_kWh','E_Load_kWh', ...
        'Deficit_total_kWh','Deficit_max_kW','Deficit_n_passos', ...
        'Tempo_min','Pfc_meta_kW','Pfc_refino_kW','Deficit_kW'});
end
